apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: racarlosdavid/mysql_gcpf_tarea3
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend
          image: racarlosdavid/api_gcpf_tarea3
          env:
          - name: MYSQL_HOST 
            value: 
          - name: MYSQL_USER 
            value: 
          - name: MYSQL_PASSWORD 
            value: 
          - name: MYSQL_DATABASE 
            value: 
          ports:
            - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  labels:
    app: backend-deployment
spec:
  type: ClusterIP
  selector:
    app: backend-deployment
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP